import React, { useEffect, useMemo, useState } from 'react';
import { supabase } from './lib/supabase';
import './styles.css';

const emptyForm = { name:'', kind:'consumible', category:'Otros', scope:'generico', brand:'', stock_nucleo:0, stock_sf:0, reorder_nucleo:10, reorder_sf:5, lead_time_days:15, total_qty:0 };

function App(){
  const [session,setSession]=useState(null), [tab,setTab]=useState('dashboard'), [items,setItems]=useState([]), [destinations,setDestinations]=useState([]), [movements,setMovements]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState('');
  const [showItem,setShowItem]=useState(false), [form,setForm]=useState(emptyForm), [saving,setSaving]=useState(false);

  useEffect(()=>{ supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return ()=>subscription.unsubscribe(); },[]);
  useEffect(()=>{ if(session) load(); },[session]);
  useEffect(()=>{ if(!session) return; const channel=supabase.channel('neostar-live').on('postgres_changes',{event:'*',schema:'public',table:'items'},load).on('postgres_changes',{event:'*',schema:'public',table:'movements'},load).on('postgres_changes',{event:'*',schema:'public',table:'destinations'},load).subscribe(); return ()=>supabase.removeChannel(channel); },[session]);

  async function load(){ setLoading(true); setError(''); const [i,d,m]=await Promise.all([supabase.from('items').select('*').order('name'),supabase.from('destinations').select('*').order('name'),supabase.from('movements').select('*,items(name),destinations(name)').order('fecha',{ascending:false}).limit(100)]); const first=i.error||d.error||m.error; if(first)setError(first.message); setItems(i.data||[]);setDestinations(d.data||[]);setMovements(m.data||[]);setLoading(false); }
  async function signIn(e){e.preventDefault(); const email=e.currentTarget.email.value,password=e.currentTarget.password.value; const r=await supabase.auth.signInWithPassword({email,password}); if(r.error)setError(r.error.message);}
  async function signOut(){await supabase.auth.signOut();}
  async function createItem(e){e.preventDefault();setSaving(true);const payload={...form,stock_nucleo:+form.stock_nucleo,stock_sf:+form.stock_sf,reorder_nucleo:+form.reorder_nucleo,reorder_sf:+form.reorder_sf,lead_time_days:+form.lead_time_days,total_qty:+form.total_qty}; const r=await supabase.from('items').insert(payload);setSaving(false);if(r.error)setError(r.error.message);else{setShowItem(false);setForm(emptyForm);load();}}
  async function createMovement(){const item=items.find(x=>x.kind==='consumible');if(!item)return alert('Primero cargá un consumible.');const qty=Number(prompt(`Cantidad para ${item.name}:`));if(!qty||qty<1)return;const r=await supabase.rpc('register_movement',{p_item_id:item.id,p_type:'compra',p_qty:qty,p_fecha:new Date().toISOString().slice(0,10),p_person:session.user.email});if(r.error)setError(r.error.message);else load();}

  if(!session)return <Login onSubmit={signIn} error={error}/>;
  const alerts=items.filter(x=>x.kind==='consumible'&&((x.stock_nucleo||0)<=(x.reorder_nucleo||0)||(x.stock_sf||0)<=(x.reorder_sf||0)));
  return <div className="app"><aside><div className="brand">NEOSTAR<span>Control de stock</span></div>{['dashboard','stock','movimientos','destinos'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{labels[x]}</button>)}<div className="user">{session.user.email}<button onClick={signOut}>Salir</button></div></aside><main><header><div><h1>{labels[tab]}</h1><p>Depósito central y puntos de entrega</p></div><div className="live">● Sincronización activa</div></header>{error&&<div className="error">{error}</div>}{loading?<div className="card">Cargando…</div>:tab==='dashboard'?<Dashboard items={items} alerts={alerts} movements={movements}/>:tab==='stock'?<Stock items={items} onNew={()=>setShowItem(true)}/>:tab==='movimientos'?<Movements movements={movements} onNew={createMovement}/>:<Destinations destinations={destinations}/>}</main>{showItem&&<ItemModal form={form} setForm={setForm} onClose={()=>setShowItem(false)} onSubmit={createItem} saving={saving}/>}</div>;
}
const labels={dashboard:'Dashboard',stock:'Stock',movimientos:'Movimientos',destinos:'Puntos de entrega'};
function Login({onSubmit,error}){return <div className="login"><form onSubmit={onSubmit} className="login-card"><div className="brand">NEOSTAR<span>Control de stock</span></div><h2>Ingresar</h2><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Contraseña" required/><button className="primary">Ingresar</button>{error&&<div className="error">{error}</div>}</form></div>}
function Dashboard({items,alerts,movements}){return <><section className="stats"><Stat n={items.length} t="Materiales"/><Stat n={alerts.length} t="Alertas" tone="warn"/><Stat n={movements.length} t="Movimientos"/><Stat n={items.filter(x=>x.kind==='equipamiento').length} t="Equipamiento"/></section><div className="card"><h2>Alertas de stock</h2>{alerts.length?<table><tbody>{alerts.map(x=><tr key={x.id}><td>{x.name}</td><td>Depo: {x.stock_nucleo} / {x.reorder_nucleo}</td><td>Santa Fe: {x.stock_sf} / {x.reorder_sf}</td><td><b className="warn">Pedir</b></td></tr>)}</tbody></table>:<p className="muted">No hay alertas.</p>}</div><div className="card"><h2>Últimos movimientos</h2><Movements movements={movements.slice(0,5)} compact/></div></>}
function Stat({n,t,tone=''}){return <div className={'stat '+tone}><strong>{n}</strong><span>{t}</span></div>}
function Stock({items,onNew}){return <div className="card"><div className="card-head"><h2>Materiales</h2><button className="primary" onClick={onNew}>+ Nuevo material</button></div>{items.length?<table><thead><tr><th>Nombre</th><th>Tipo</th><th>Categoría</th><th>Depo Central</th><th>Santa Fe</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.name}</b>{x.brand&&<small>{x.brand}</small>}</td><td>{x.kind==='consumible'?'Consumible':'Equipamiento'}</td><td>{x.category}</td><td><StockValue value={x.stock_nucleo} min={x.reorder_nucleo}/></td><td><StockValue value={x.stock_sf} min={x.reorder_sf}/></td></tr>)}</tbody></table>:<p className="muted">No hay materiales.</p>}</div>}
function StockValue({value,min}){return <span className={value<=min?'warn':''}>{value} <small>/ mínimo {min}</small></span>}
function Movements({movements,onNew,compact}){return <div className="card"><div className="card-head"><h2>{compact?'':'Historial de movimientos'}</h2>{onNew&&!compact&&<button className="primary" onClick={onNew}>+ Compra rápida</button>}</div>{movements.length?<table><thead><tr><th>Fecha</th><th>Material</th><th>Tipo</th><th>Cantidad</th><th>Responsable</th></tr></thead><tbody>{movements.map(x=><tr key={x.id}><td>{x.fecha}</td><td>{x.items?.name||'—'}</td><td>{x.type}</td><td>{x.qty}</td><td>{x.person||'—'}</td></tr>)}</tbody></table>:<p className="muted">No hay movimientos.</p>}</div>}
function Destinations({destinations}){return <div className="card"><h2>Puntos de entrega</h2>{destinations.length?<table><thead><tr><th>Nombre</th><th>Marcas</th><th>Abastecido por</th></tr></thead><tbody>{destinations.map(x=><tr key={x.id}><td>{x.name}</td><td>{(x.marcas||[]).join(', ')||'Genérico'}</td><td>{x.abastecido_por==='nucleo'?'Depo Central':'Santa Fe'}</td></tr>)}</tbody></table>:<p className="muted">No hay puntos configurados.</p>}</div>}
function ItemModal({form,setForm,onClose,onSubmit,saving}){const set=(k,v)=>setForm({...form,[k]:v});return <div className="modal-bg"><form className="modal" onSubmit={onSubmit}><h2>Nuevo material</h2><input required placeholder="Nombre" value={form.name} onChange={e=>set('name',e.target.value)}/><div className="grid"><select value={form.kind} onChange={e=>set('kind',e.target.value)}><option value="consumible">Consumible</option><option value="equipamiento">Equipamiento</option></select><input placeholder="Categoría" value={form.category} onChange={e=>set('category',e.target.value)}/></div><div className="grid"><input type="number" placeholder="Stock Depo" value={form.stock_nucleo} onChange={e=>set('stock_nucleo',e.target.value)}/><input type="number" placeholder="Stock Santa Fe" value={form.stock_sf} onChange={e=>set('stock_sf',e.target.value)}/></div><div className="grid"><input type="number" placeholder="Mínimo Depo" value={form.reorder_nucleo} onChange={e=>set('reorder_nucleo',e.target.value)}/><input type="number" placeholder="Mínimo Santa Fe" value={form.reorder_sf} onChange={e=>set('reorder_sf',e.target.value)}/></div><div className="actions"><button type="button" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving?'Guardando…':'Crear material'}</button></div></form></div>}

export default App;
