import React, { useEffect, useMemo, useState } from 'react';
import { supabase } from './lib/supabase';
import './styles.css';

const CATEGORIES = ['Indumentaria y textil','Bazar y estilo de vida','Accesorios y tecnología','Car care / accesorios de auto','Portapatentes','Portadocumentos','Stickers Domo','Regalos','Equipamiento de eventos','Otros'];
const SUBCATEGORIES = ['Gorras y sombreros','Remeras y chombas','Camperas y buzos','Mochilas y bolsos','Termos, mates y vasos','Botellas','Paraguas y camping','Llaveros y pines','Librería','Powerbanks y cargadores','Anteojos y relojes','Limpieza vehicular','Herramientas e infladores','Roll banners','Sillas','Mesas','Otros'];
const BRANDS = ['Kia','Jeep','RAM','Nissan','BYD','Suzuki','Subaru','Honda','Neostar','Genérico'];
const LOCATIONS = ['Depo Central','Depósito Santa Fe','Punto de entrega'];
const emptyItem = { name:'', sku:'', kind:'consumible', category:'Otros', subcategory:'', scope:'generico', brand:'', occasion:'', stock_nucleo:0, stock_sf:0, reorder_nucleo:10, reorder_sf:5, lead_time_days:15, total_qty:0 };

export default function App(){
 const [session,setSession]=useState(null),[tab,setTab]=useState('dashboard'),[items,setItems]=useState([]),[destinations,setDestinations]=useState([]),[movements,setMovements]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [showItem,setShowItem]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(emptyItem),[query,setQuery]=useState(''),[category,setCategory]=useState('Todas'),[brand,setBrand]=useState('Todas');
 const [showMove,setShowMove]=useState(false),[move,setMove]=useState({item_id:'',type:'retiro',qty:1,origin:'Depo Central',destination:'',reason_type:'operativo',reason_detail:'',recipient_last_name:'',notes:''});
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session) load()},[session]);
 useEffect(()=>{if(!session)return;const ch=supabase.channel('neostar-live').on('postgres_changes',{event:'*',schema:'public',table:'items'},load).on('postgres_changes',{event:'*',schema:'public',table:'movements'},load).subscribe();return()=>supabase.removeChannel(ch)},[session]);
 async function load(){setLoading(true);const [a,b,c]=await Promise.all([supabase.from('items').select('*').order('name'),supabase.from('destinations').select('*').order('name'),supabase.from('movements').select('*,items(name)').order('created_at',{ascending:false}).limit(100)]);if(a.error)setError(a.error.message);setItems(a.data||[]);setDestinations(b.data||[]);setMovements(c.data||[]);setLoading(false)}
 async function signIn(e){e.preventDefault();const r=await supabase.auth.signInWithPassword({email:e.currentTarget.email.value,password:e.currentTarget.password.value});if(r.error)setError(r.error.message)}
 async function saveItem(e){e.preventDefault();setError('');const p={...form,stock_nucleo:+form.stock_nucleo||0,stock_sf:+form.stock_sf||0,reorder_nucleo:+form.reorder_nucleo||0,reorder_sf:+form.reorder_sf||0,lead_time_days:+form.lead_time_days||0,total_qty:+form.total_qty||0};const r=editing?await supabase.from('items').update(p).eq('id',editing):await supabase.from('items').insert(p);if(r.error){setError(r.error.message);return}setShowItem(false);setEditing(null);setForm(emptyItem);load()}
 function openEdit(item){setEditing(item.id);setForm({...emptyItem,...item});setShowItem(true)}
 async function removeItem(item){if(!confirm(`¿Eliminar ${item.name}? Esta acción no se puede deshacer.`))return;const r=await supabase.from('items').delete().eq('id',item.id);if(r.error)setError(r.error.message);else load()}
 async function saveMovement(e){e.preventDefault();setError('');if(!move.item_id||!move.qty)return;const r=await supabase.rpc('register_movement',{p_item_id:move.item_id,p_type:move.type,p_qty:+move.qty,p_fecha:new Date().toISOString().slice(0,10),p_person:move.reason_detail||null,p_reason_type:move.reason_type,p_reason_detail:move.reason_detail,p_recipient_last_name:move.recipient_last_name||null,p_origin:move.origin,p_destination:move.destination||null});if(r.error){setError(r.error.message);return}setShowMove(false);setMove({...move,item_id:'',qty:1,reason_detail:'',recipient_last_name:'',notes:''});load()}
 const alerts=items.filter(x=>x.kind==='consumible'&&((x.stock_nucleo||0)<=(x.reorder_nucleo||0)||(x.stock_sf||0)<=(x.reorder_sf||0)));
 const filtered=useMemo(()=>items.filter(x=>(x.name+' '+(x.sku||'')+' '+(x.brand||'')).toLowerCase().includes(query.toLowerCase())&&(category==='Todas'||x.category===category)&&(brand==='Todas'||x.brand===brand)),[items,query,category,brand]);
 if(!session)return <Login onSubmit={signIn} error={error}/>;
 return <div className="app"><aside><div className="brand">NEOSTAR<span>Control de stock</span></div>{[['dashboard','Dashboard'],['stock','Materiales'],['movimientos','Movimientos'],['destinos','Puntos de entrega']].map(([k,l])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{l}</button>)}<div className="side-bottom"><button onClick={()=>supabase.auth.signOut()}>Cerrar sesión</button></div></aside><main><header><div><small>Gestión de inventario</small><h1>{({dashboard:'Dashboard',stock:'Materiales',movimientos:'Movimientos',destinos:'Puntos de entrega'})[tab]}</h1></div><button className="primary" onClick={()=>{setError('');setShowMove(true)}}>+ Registrar retiro</button></header>{error&&<div className="error">{error}</div>}{loading?<div className="card">Cargando…</div>:tab==='dashboard'?<Dashboard items={items} alerts={alerts} movements={movements}/>:tab==='stock'?<Stock items={filtered} query={query} setQuery={setQuery} category={category} setCategory={setCategory} brand={brand} setBrand={setBrand} onNew={()=>{setEditing(null);setForm(emptyItem);setShowItem(true)}} onEdit={openEdit} onDelete={removeItem}/>:tab==='movimientos'?<Movements rows={movements} onNew={()=>setShowMove(true)}/>:<Destinations rows={destinations}/>}</main>{showItem&&<ItemModal form={form} setForm={setForm} editing={editing} onClose={()=>setShowItem(false)} onSubmit={saveItem}/>} {showMove&&<MovementModal move={move} setMove={setMove} items={items.filter(x=>x.kind==='consumible')} destinations={destinations} onClose={()=>setShowMove(false)} onSubmit={saveMovement}/>}</div>
}
function Login({onSubmit,error}){return <div className="login"><form className="login-card" onSubmit={onSubmit}><div className="brand">NEOSTAR<span>Control de stock</span></div><h2>Ingresar</h2><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Contraseña" required/><button className="primary">Ingresar</button>{error&&<p className="error">{error}</p>}</form></div>}
function Dashboard({items,alerts,movements}){return <><section className="stats"><Stat n={items.length} t="Materiales"/><Stat n={alerts.length} t="Alertas de stock" tone="warn"/><Stat n={movements.length} t="Movimientos"/><Stat n={items.reduce((a,x)=>a+(+x.stock_nucleo||0)+(+x.stock_sf||0),0)} t="Unidades centrales"/></section><div className="grid"><section className="card"><h2>Alertas</h2>{alerts.length?<table><thead><tr><th>Material</th><th>Central</th><th>Santa Fe</th></tr></thead><tbody>{alerts.slice(0,8).map(x=><tr key={x.id}><td>{x.name}</td><td className="warn">{x.stock_nucleo||0} / {x.reorder_nucleo||0}</td><td>{x.stock_sf||0} / {x.reorder_sf||0}</td></tr>)}</tbody></table>:<p className="muted">No hay alertas.</p>}</section><section className="card"><h2>Últimos movimientos</h2>{movements.slice(0,6).map(m=><div className="activity" key={m.id}><b>{m.items?.name||'Material'}</b><span>{m.type} · {m.qty} unidades</span></div>)}</section></div></>}
function Stat({n,t,tone}){return <div className={'stat '+(tone||'')}><strong>{n}</strong><span>{t}</span></div>}
function Stock({items,query,setQuery,category,setCategory,brand,setBrand,onNew,onEdit,onDelete}){return <section className="card"><div className="card-head"><div><h2>Materiales</h2><p className="muted">Clasificación por categoría, marca y SKU</p></div><button className="primary" onClick={onNew}>+ Nuevo material</button></div><div className="filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nombre, SKU o marca…"/><select value={category} onChange={e=>setCategory(e.target.value)}><option>Todas</option>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select><select value={brand} onChange={e=>setBrand(e.target.value)}><option>Todas</option>{BRANDS.map(x=><option key={x}>{x}</option>)}</select></div><table><thead><tr><th>Material / SKU</th><th>Categoría</th><th>Marca</th><th>Central</th><th>Santa Fe</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.sku||'Sin SKU'}</small></td><td>{x.category}<small>{x.subcategory}</small></td><td>{x.brand||'Genérico'}</td><td><StockValue value={x.stock_nucleo} min={x.reorder_nucleo}/></td><td><StockValue value={x.stock_sf} min={x.reorder_sf}/></td><td className="actions"><button onClick={()=>onEdit(x)}>Editar</button><button className="danger-link" onClick={()=>onDelete(x)}>Eliminar</button></td></tr>)}</tbody></table>{!items.length&&<p className="muted empty">No hay materiales con esos filtros.</p>}</section>}
function StockValue({value,min}){return <span className={(value||0)<= (min||0)?'warn':''}>{value||0}<small> mín. {min||0}</small></span>}
function Movements({rows,onNew}){return <section className="card"><div className="card-head"><div><h2>Historial de movimientos</h2><p className="muted">Cada retiro debe indicar un motivo y, si corresponde, apellido del cliente.</p></div><button className="primary" onClick={onNew}>+ Registrar retiro</button></div><table><thead><tr><th>Fecha</th><th>Material</th><th>Tipo</th><th>Cantidad</th><th>Motivo</th><th>Responsable</th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td>{m.fecha||new Date(m.created_at).toLocaleDateString('es-AR')}</td><td>{m.items?.name||m.item_id}</td><td>{m.type}</td><td>{m.qty}</td><td>{m.reason_detail||m.person||'—'}{m.recipient_last_name&&<small>Cliente: {m.recipient_last_name}</small>}</td><td>{m.person||'—'}</td></tr>)}</tbody></table></section>}
function Destinations({rows}){return <section className="card"><h2>Puntos de entrega</h2><table><thead><tr><th>Nombre</th><th>Marcas</th><th>Abastecido por</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.name}</td><td>{(x.marcas||[]).join(', ')}</td><td>{x.abastecido_por}</td></tr>)}</tbody></table></section>}
function ItemModal({form,setForm,editing,onClose,onSubmit}){const set=(k,v)=>setForm({...form,[k]:v});return <div className="modal-bg"><form className="modal" onSubmit={onSubmit}><div className="card-head"><h2>{editing?'Editar material':'Nuevo material'}</h2><button type="button" onClick={onClose}>×</button></div><div className="form-grid"><label>Nombre<input required value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>SKU<input value={form.sku} onChange={e=>set('sku',e.target.value.toUpperCase())} placeholder="NIS-ACC-LLA01"/></label><label>Macrocategoría<select value={form.category} onChange={e=>set('category',e.target.value)}>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></label><label>Subcategoría<select value={form.subcategory} onChange={e=>set('subcategory',e.target.value)}><option value="">Seleccionar</option>{SUBCATEGORIES.map(x=><option key={x}>{x}</option>)}</select></label><label>Marca<select value={form.brand} onChange={e=>set('brand',e.target.value)}><option value="">Genérico</option>{BRANDS.map(x=><option key={x}>{x}</option>)}</select></label><label>Tipo<select value={form.kind} onChange={e=>set('kind',e.target.value)}><option value="consumible">Consumible</option><option value="equipamiento">Equipamiento</option></select></label><label>Ocasión<input value={form.occasion} onChange={e=>set('occasion',e.target.value)} placeholder="Nuevo, service, postventa…"/></label><label>Stock central<input type="number" min="0" value={form.stock_nucleo} onChange={e=>set('stock_nucleo',e.target.value)}/></label><label>Mínimo central<input type="number" min="0" value={form.reorder_nucleo} onChange={e=>set('reorder_nucleo',e.target.value)}/></label><label>Stock Santa Fe<input type="number" min="0" value={form.stock_sf} onChange={e=>set('stock_sf',e.target.value)}/></label><label>Mínimo Santa Fe<input type="number" min="0" value={form.reorder_sf} onChange={e=>set('reorder_sf',e.target.value)}/></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancelar</button><button className="primary">Guardar material</button></div></form></div>}
function MovementModal({move,setMove,items,destinations,onClose,onSubmit}){const set=(k,v)=>setMove({...move,[k]:v});return <div className="modal-bg"><form className="modal" onSubmit={onSubmit}><div className="card-head"><h2>Registrar retiro</h2><button type="button" onClick={onClose}>×</button></div><p className="muted">El registro quedará asociado al usuario que inició sesión.</p><div className="form-grid"><label>Material<select required value={move.item_id} onChange={e=>set('item_id',e.target.value)}><option value="">Seleccionar material</option>{items.map(x=><option key={x.id} value={x.id}>{x.name} · {x.brand||'Genérico'}</option>)}</select></label><label>Cantidad<input required type="number" min="1" value={move.qty} onChange={e=>set('qty',e.target.value)}/></label><label>Origen<select value={move.origin} onChange={e=>set('origin',e.target.value)}>{LOCATIONS.map(x=><option key={x}>{x}</option>)}</select></label><label>Destino<select value={move.destination} onChange={e=>set('destination',e.target.value)}><option value="">Retiro / uso interno</option>{destinations.map(x=><option key={x.id}>{x.name}</option>)}</select></label><label>Motivo<select value={move.reason_type} onChange={e=>set('reason_type',e.target.value)}><option value="operativo">Operativo / reposición</option><option value="incidencia_cliente">Incidencia con cliente</option><option value="regalo_especial">Regalo corporativo o especial</option><option value="visita">Visita importante</option><option value="evento">Evento</option><option value="otro">Otro</option></select></label><label>Apellido del cliente{move.reason_type==='incidencia_cliente'?<input required value={move.recipient_last_name} onChange={e=>set('recipient_last_name',e.target.value)} placeholder="Apellido requerido"/>:<input value={move.recipient_last_name} onChange={e=>set('recipient_last_name',e.target.value)}/>}</label><label className="wide">Detalle / descripción<input required value={move.reason_detail} onChange={e=>set('reason_detail',e.target.value)} placeholder="Ej.: Regalo futbolista Central retira BYD"/></label><label className="wide">Notas<textarea value={move.notes} onChange={e=>set('notes',e.target.value)}/></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancelar</button><button className="primary">Registrar retiro</button></div></form></div>}
